### PR TITLE
Marcos routing auth

### PR DESCRIPTION
**Pull request by marcosignorello**
- Added routing
- Added authentication
- Added theme files and provider

### CODE REVIEW

**Review by balveda — COMMENTED** [review]
Not sure if this will appear in the right place but...
 in layout/layout.tsx, don't we want the AppHeader to be inside the ThemeProvider?

**Comment by marcosignorello** [comment]
> Not sure if this will appear in the right place but...
> in layout/layout.tsx, don't we want the AppHeader to be inside the ThemeProvider?

Good catch, thanks. I have update it

**Comment by dhargitai** [comment]
Looks good to me 👍

**Comment by StellarLogic** [comment]
great :fire:

**Pull request merged**
